train:
  batch_size_train: 4
  num_workers_train: 0
  batch_size_test: 4  
  num_workers_test: 0 

  epochs: 1000 
  amp: True

  optim: "adamw"
  lr: 0.0002
  weight_decay: 0.0001

  scheduler: "cosine"
  eta_min: 0.000001

  lambda_sam: 0.1

  metrics_report_interval: 5

  balance_cats: False

model:
  model_name: "raw2hsi"
  
  base_ch: 64
  n_blocks: 8
  out_bands: 61

transforms:
  random_crop: False
  crop_size: 320
  random_flip: False
