train:
  batch_size_train: 2
  num_workers_train: 0
  batch_size_test: 2  
  num_workers_test: 0 

  fast:
     num_workers_train_in: 2
     num_workers_train_out: 2
     
     num_workers_test_in: 2
     num_workers_test_out: 2

  epochs: 1000 
  amp: True

  optim: "adamw"
  lr: 0.0002
  weight_decay: 0.0001

  scheduler: "cosine"
  eta_min: 0.000001

  lambda_sam: 0.1

  metrics_report_interval: 0

model:
  model_name: "revsci_rgb"

  # revsci params
  n_blocks: 12
  n_split: 2
  
transforms:
  random_crop: False
  crop_size: 256
  random_flip: False # might not work with revsci - makes mosaic not match expectation
