train:
  batch_size_train: 1
  batch_size_test: 1  

  num_workers_train: 0
  num_workers_test: 0 
  fast:
    num_workers_train_in: 2 
    num_workers_train_out: 2 

    num_workers_test_in: 2  
    num_workers_test_out: 2  

  epochs: 1000 
  amp: True

  optim: "adamw"
  lr: 0.0004
  weight_decay: 0.0001

  scheduler: "cosine"
  eta_min: 0.000001

  lambda_sam: 0.1

  metrics_report_interval: 5

model:
  model_name: "revsci_mstpp_up"

  # replace with pre-trained revsci path
  pretrained_revsci_path: "runs/track2/revsci_rgb_up_crop256/model_best.tar"

  # revsci params
  n_blocks: 12
  n_split: 2
  old_mode: False # some pre-trained models will require this to be True
  
  # mst++ params
  in_channels: 3 
  out_channels: 61
  n_feat: 61 
  stage: 3 
  upscale_factor: 2

transforms:
  random_crop: True
  crop_size: 256

  random_flip: False
  random_rot90: False

  rgb_gaussian_noise: False
  rgb_noise_sigma: 0.01

  spectral_jitter: False
  spectral_jiter_sigma: 0.02
