train:
  batch_size_train: 3  
  batch_size_test: 1   

  num_workers_train: 0 
  num_workers_test: 0  

  fast:
    num_workers_train_in: 2
    num_workers_train_out: 2 

    num_workers_test_in: 2  
    num_workers_test_out: 2  

  epochs: 1000 
  amp: True

  optim: "adam"
  lr: 0.0002
  weight_decay: 0

  scheduler: "cosine"
  eta_min: 0.000001

  lambda_sam: 0.1

  metrics_report_interval: 5

  balance_cats: False

model:
  model_name: "revsci_mstpp_no_pretrain"

  # revsci params
  n_blocks: 16
  n_split: 2
  old_mode: true
  
  # mst++ params
  in_channels: 3 
  out_channels: 61
  n_feat: 61 
  stage: 3 
  upscale_factor: 1

transforms:
  random_crop: true
  crop_size: 256

  random_flip: True
  random_rot90: True

  rgb_gaussian_noise: True
  rgb_noise_sigma: 0.01

  spectral_jitter: True
  spectral_jiter_sigma: 0.02
